#!/usr/bin/env bash

valid_ip ()
{
    local  ip=$1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
    else
        return 1
    fi
}

if [ "$1" = "-r" ];then
    #create the catchers array to keep track of the users
    catchers=()
    #create an index var
    index=0

    #read the sshd_config file for entries
    while IFS= read -r line
    do
        ((index++))
        catchers[$index]=${line:16}
        echo "$index. ${line:16}"
    done < <(grep "#throwcatchuser" /etc/ssh/sshd_config)

    if [[ $index -eq 0 ]];then
        echo "No users to remove."
        exit 1
    fi

    while [[ ! $catcher ]] || [[ $catcher -lt 1 ]] || [[ $catcher -gt $index ]];do
        read -p 'Choose a catcher from the list to delete: ' catcher
    done

    #fetch the username
    username="${catchers[$catcher]%%@*}"
    #delete tghe user from /etc/passwd
    userdel $username
    #remove the users folder
    rm -rf /home/$username

    #remove the entry in the sshd_config file
    sed -i "/\#throwcatchuser ${catchers[$catcher]}/,/\#\/throwcatchuser ${catchers[$catcher]}/d" /etc/ssh/sshd_config

    #restart sshd
    service sshd restart

    echo "${catchers[$catcher]} removed..."

    exit 0
fi
    
# this is effectively how to tell if this is the first run
if ! grep -q '^ssh$' /etc/securetty;then
    printf "\nssh" >> /etc/securetty
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config_ORIG
fi

#prompt for thrower username
read -p $'What\'s the name of your new thrower?\n' name
while [[ ! $name ]] || id -u "$name" &> /dev/null; do
    read -p $'Please choose a valid name...\n' name
done

#prompt for thrower ip
read -p $'What\'s the IP address of your new thrower?\n' ip
while ! valid_ip $ip;do
    read -p $'Please provide a valid IP address...\n' ip
done

#check if the user already exists, if it does, kill the process
exists=0
while IFS= read -r line
do
    ((exists++))
done < <(grep "#throwcatchuser $name@$ip" /etc/ssh/sshd_config)

if [[ $exists -gt 0 ]];then
    echo "$name@$ip already exists"
    exit 1
fi

#add the user
useradd $name
#set the passwd to nothing
passwd -d $name
#make the home folder
mkdir /home/$name
#make the catches folder
mkdir /home/$name/catches
#set up the rights for the catches folder
chown $name:$name /home/$name/catches
chmod 700 /home/$name/catches

cat << EOF >> /etc/ssh/sshd_config

#throwcatchuser $name@$ip
#IF YOU DELETE THE ABOVE LINE, catch WON'T BE ABLE TO REMOVE THE USER FROM THIS CONFIG FILE
Match User $name Address $ip
PasswordAuthentication yes
PermitEmptyPasswords yes
PubkeyAuthentication no
ChrootDirectory /home/$name
ForceCommand internal-sftp -p open,close,write,stat,realpath,fsetstat
PermitTunnel no
AllowAgentForwarding no
AllowTcpForwarding no
x11Forwarding no
#IF YOU DELETE THE BELOW LINE, catch WON'T BE ABLE TO REMOVE THE USER FROM THIS CONFIG FILE
#/throwcatchuser $name@$ip
EOF

echo "Thrower $name added..."

service sshd restart
